config/routes.rb
Rails.application.routes.draw do
  get 'logs/import'
  resources :logs

end

app/models/log.rb
class Log < ActiveRecord::Base
	
	self.table_name="logs"

	ERR_LOGS = {
		'111' => 'SUCCESS',
		'000' => 'FAILURE',			
		'001' => 'DUPLICATE_USER',	
		'010' => 'USER_NO_EXIST',		
		'011' => 'BAD_PERMISSIONS',	
		'100' => 'BAD_CHECKSUM',		
		'101' => 'FATAL_ERROR',		
		'110' => 'BAD_IP',			
	}

	OP = [
		'ADD',
		'UPDATE',
		'REMOVE',
	]

	ERR_LOGS_SEPARATOR = "-"

	def create_from_array (s, site)
		self.operation_type = s[0]
		self.date = s[1]
		self.username = s[2]
		self.second_date = s[3]
		self.ip = s[4]
		self.site = site
	end
	
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  before_action :set_log, only: [:show, :edit, :update, :destroy]

  # GET /logs
  # GET /logs.json
  def index
    @logs = Log.where(:site=>params[:site])
    @rejected = Log.joins('logs join `logs` l2 on l2.`username` = `logs`.`username`')
      .where('logs.operation_type = \'ADD-111\' and l2.operation_type=\'REMOVE-111\' and ABS(l2.date-logs.date) < 100 and logs.site =\''+params[:site]+'\'')
  end

  # GET /logs/1
  # GET /logs/1.json
  def show
  end


  def import 
    lines = File.readlines('/var/www/digester/tmp/ccbill.log')
    lines.each do |l|
      log = Log.new
      log.create_from_array(l.split(/\|/),params[:site])
      log.save
    end
  end

  # GET /logs/new
  def new
    @log = Log.new
  end

  # GET /logs/1/edit
  def edit
  end

  # POST /logs
  # POST /logs.json
  def create
    @log = Log.new(log_params)

    respond_to do |format|
      if @log.save
        format.html { redirect_to @log, notice: 'Log was successfully created.' }
        format.json { render :show, status: :created, location: @log }
      else
        format.html { render :new }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /logs/1
  # PATCH/PUT /logs/1.json
  def update
    respond_to do |format|
      if @log.update(log_params)
        format.html { redirect_to @log, notice: 'Log was successfully updated.' }
        format.json { render :show, status: :ok, location: @log }
      else
        format.html { render :edit }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logs/1
  # DELETE /logs/1.json
  def destroy
    @log.destroy
    respond_to do |format|
      format.html { redirect_to logs_url }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_log
      @log = Log.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def log_params
      params.require(:log).permit(:operation_type, :date, :username, :second_date,  :ip, :site)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logs_helper.rb
module LogsHelper
	
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Digester</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/logs/_form.html.erb
<%= form_for(@log) do |f| %>
  <% if @log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@log.errors.count, "error") %> prohibited this log from being saved:</h2>

      <ul>
      <% @log.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :operation_type %><br>
    <%= f.text_field :operation_type %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.text_field :date %>
  </div>
  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :second_date %><br>
    <%= f.text_field :second_date %>
  </div>
  <div class="field">
    <%= f.label :ip %><br>
    <%= f.text_field :ip %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/logs/edit.html.erb
<h1>Editing log</h1>

<%= render 'form' %>

<%= link_to 'Show', @log %> |
<%= link_to 'Back', logs_path %>

app/views/logs/import.html.haml
%section.container
  %h1= "Import ok!"
  .content
    %h2= Log.count.to_s + " log count"

app/views/logs/index.html.haml
%section.container
  %h1= "Listing logs"
  =Log::ERR_LOGS.to_s
  
  .content
    %h2= "Op types"
    = pie_chart @logs.group(:operation_type).count
    %h2= "Remove ok by week"
    = area_chart @logs.where(:operation_type => Log::OP.reverse.first.to_s + Log::ERR_LOGS_SEPARATOR + Log::ERR_LOGS.first.first.to_s).group_by_week(:date).count

    %h2= "Remove ok by month"
    = area_chart @logs.where(:operation_type => Log::OP.reverse.first.to_s + Log::ERR_LOGS_SEPARATOR + Log::ERR_LOGS.first.first.to_s).group_by_month(:date).count
    
    %h2= "Op types by week"
    =area_chart @logs.group(:operation_type).map{|log|{name: log.operation_type, data: @logs.where(operation_type:log.operation_type).group_by_week(:date).count}}

    %h2= "Op types by month"
    =area_chart @logs.group(:operation_type).map{|log|{name: log.operation_type, data: @logs.where(operation_type:log.operation_type).group_by_month(:date).count}}

    %h2= "Rejected"
    =line_chart @rejected.group_by_day('logs.date').count

    %h2= "Rejected by month"
    =line_chart @rejected.group_by_month('logs.date').count

    %h2= "Rejected by week"
    =line_chart @rejected.group_by_week('logs.date').count

    %h2= "Errors.log"
    =area_chart @logs.where('operation_type not like \'%111\'').group_by_week(:date).count

    

    %h2= "AVG time user on site"
    

app/views/logs/new.html.erb
<h1>New log</h1>

<%= render 'form' %>

<%= link_to 'Back', logs_path %>

app/views/logs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Operation type:</strong>
  <%= @log.operation_type %>
</p>

<p>
  <strong>Date:</strong>
  <%= @log.date %>
</p>

<p>
  <strong>Username:</strong>
  <%= @log.username %>
</p>

<p>
  <strong>Second date:</strong>
  <%= @log.second_date %>
</p>

<p>
  <strong>Ip:</strong>
  <%= @log.ip %>
</p>

<%= link_to 'Edit', edit_log_path(@log) %> |
<%= link_to 'Back', logs_path %>